import pet from './header'
import blockContent from './blockContent'
import headerinfo from './header-info'
import hero from './hero'
import footer from './footer'
import passport from './passport'
import avantages from './avantages'
import nft from './nft'
import qrcode from './qrcode'
import pageFooter from './pageFooter'
import video from './video'
export const schemaTypes = [blockContent,pet,headerinfo,hero, passport, avantages,nft, qrcode,video, footer, pageFooter]
